site_name: EOSC-SYNERGY Link List of WP2
site_dir: /tmp/synergy-wp2
docs_dir: ..
repo_url: https://github.com/EOSC-synergy/wp2-links
edit_uri: "edit/master"
theme: 
    name: 'readthedocs'
    # name: 'rtd-mklab'
    # name: 'rtd-dropdown'
    # name: mkdocs
    hightlightjs: true
markdown_extensions:
    - smarty
    - toc:
        baselevel: 1
        permalink: "#"
    - admonition
    - def_list
nav:
    - Home: index.md
    - ----------: /
    - Infrastructure 101: infra_101.md
    - Organisation of infrastructure: infra_organisation.md
    - How to get access: how-to-get-access.md
    - How to use the infrastructure: infra_howto.md
    - How to get Ressources: ressources_howto.md
    - Virtual Organisations: vos.md
    - Cloud Infrastructure: cloud.md
    - ----------: /
    - Tools: tools.md
    - ----------: /
    #- Infrastructure: infrastructure.md
    - Accounting: accounting-links.md
    #- Notes on Storage: storage.md
    - Internal Link Collection: internal.md
    - ----------: /
    # - Copy of the HDF Official Webpage: hdf-official-web-copy.md
    - Imprint: http://www.kit.edu/impressum.php
